app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),    
    
    path('', include('shop.urls', namespace="shop")),
    path('account/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path, include

from .views import *

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',  AddCart.as_view(), name="addcart"),
    path('remove/<int:product_id>',  RemoveCart.as_view(), name="removecart"),
    path('update/<int:product_id>/',  UpdateCart.as_view(), name="update"),
    

]

app/shop/urls.py
from django.urls import path, include

from .views import *

app_name = 'shop'

urlpatterns = [
    path('',  IndexShow.as_view(), name="home"),
    path('shop/',  ShopView.as_view(), name="shop"),
    path('search/',  SearchView.as_view(), name="search"),
    path('shop/category/<slug:slug_cat>',  CategoryView.as_view(), name="category"),
    path('shop/<slug:slug_product>',  ProductView.as_view(), name="product"),
    
]

app/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        
    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:category", kwargs={"slug_cat": self.slug})
    

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=120, db_index=True, verbose_name='Название')
    slug = models.CharField(max_length=120, db_index=True, unique=True,verbose_name='Ссылка')
    image = models.ImageField(upload_to="product/%Y/%m/%d", blank=True)
    description = models.TextField(max_length=1500, blank=True,verbose_name='Описание')
    price = models.IntegerField(verbose_name='Цена')
    available = models.BooleanField(default=True,verbose_name='Наличие')
    created = models.DateTimeField(auto_now_add=True,verbose_name='Добавление')
    uploaded = models.DateTimeField(auto_now=True,verbose_name='Изменение')
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)
        
    def __str__(self) -> str:
        return self.name
        
    def get_absolute_url(self):
        return reverse("shop:product", kwargs={"slug_product": self.slug})

app/shop/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'searchForm'
        }
    ))

app/shop/views.py
import json
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView, ListView, FormView, DetailView
from django.template.loader import render_to_string
from .models import *
from users.forms import *
from .forms import *
# Create your views here.

class IndexShow(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Succulentum'
        return context
    


class SearchView(FormView):
    def post(self, request):
        form = SearchForm(request.POST)
        search = []
        if form.is_valid():
            search = form.cleaned_data
            
        return HttpResponse(search) 
    
class ShopView(ListView):
    template_name = 'shop/shop.html'
    context_object_name = 'products'

    
    def get_context_data(self ,*args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['searchForm'] = SearchForm()
        context['title'] = 'Магазин'
        context['cat'] = Category.objects.all()
        context['cat_selected'] = 0
        
        return context
    
    def get_queryset(self):
        return Product.objects.all()
    

class CategoryView(ListView):
    template_name = 'shop/shop.html'
    context_object_name = 'products'
    
    
    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug_cat'])
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категория'
        context['searchForm'] = SearchForm()
        context['cat_selected'] = self.kwargs['slug_cat']
        context['cat'] = Category.objects.all()
        return context
    
class ProductView(DetailView):
    model = Product
    template_name = 'shop/detailProduct.html'
    slug_url_kwarg = 'slug_product'
    context_object_name = 'product'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.kwargs['slug_product']
        return context
    

app/templates/shop/detailProduct.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<main class="wrapperProduct">

    <div class="Product">


        <div class="productImage">
            <img src="{{ product.image.url }}" alt="">
        </div>
        <div >
            <div class="productName">
                <h4>{{ product.name }}</h4>
            </div>
            <div class="addCart">
                {% if not id|stringformat:"s"  in request.session.cart  %}
                <form action="{% url 'cart:addcart' product.id %}" method="POST" class="CartAdd" id="add">
                    {% csrf_token %}
                    <p class="hidden">{{addcart.quantity}}</p>
                    {{addcart.updaye}}
                    <button type="submit" class="BTNadd" id="add">В корзину</button>
                </form>
                {% else %}
                    <p>Уже в корзине </p>
                {% endif %}

            </div>
            <div class="productDescription">
                <p>
                    {{ product.description}}
                </p>
            <div>
        </div>
    </div>

    </div>
</main>

{% endblock %}

app/templates/shop/product.html
<article class="productCard">
    <div class="productPhoto">
        <img src="{{ product.image.url}} " alt="">
    </div>
    <div class="productInfo">
        <a class="cartProductName" href="{{ product.get_absolute_url}}">{{product.name}}</a>
    
        <p class="productPrice"> {{product.price}} руб </p>
        {% if not id|stringformat:"s"  in request.session.cart  %}
            <form action="{% url 'cart:addcart' id %}" method="POST" class="CartAdd" id="add">
                {% csrf_token %}
                
                <input type="hidden" name="quantity" value="1"/>
                <button type="submit" class="BTNadd" id="add">В корзину</button>
            </form>
        {% else %}
        <p>Уже в корзине </p>

        {% endif %}
    </div>

</article>

app/templates/shop/shop.html
{% extends 'base.html' %}
{% load static %}



{% block content%}

<main class="wrapperShop">
    <section class="filterShop container">
        <div class="searchShop">
            {% comment %} <div class="iconsSearch">
                <img src="{% static 'icons/search.svg' %}" alt="">
            </div> {% endcomment %}
            <form action="{% url 'shop:search' %}" id="search" method="post">
                {% csrf_token %}
                {{ searchForm.search }}
                
            </form>        
            
            <div >
                <img src="{% static "icons/menu.svg" %}" id="catalog"/>
            </div>
            <div >
                <img src="{% static "icons/close.svg" %}"  id="closeCatalog"/>
            </div>
        </div>

        <div class="catalogShopName" id="catalogName">
                {% if cat_selected == 0 %}
                    <a>Все категории</a>
                {% else %}
                    <a href="{% url 'shop:shop' %}">Все категории</a>
                {% endif %}

            {% for i in cat %}
                {% if i.slug == cat_selected %}
                    <a> {{i.name}}</a>
                {% else %}
                    <a href="{{ i.get_absolute_url }}">{{i.name}}</a>
                {% endif %}
            {% endfor %}
        </div>

    </section>
    <section class="allProductsShop container">

        {% for product in products %}
            {% include 'shop/product.html' with id=product.id %}
        {% endfor %}
    </section>
</main>


{% endblock %}