app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),    
    
    path('', include('shop.urls', namespace="shop")),
    path('account/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import *


app_name = 'users'

urlpatterns = [
    path('singup',  SingUpView.as_view(), name="singup"),
    path('singin',  SingInView.as_view(), name="singin"),
    path('logout',  Logout.as_view(), name="logout"),
    path('profil',  Profil.as_view(), name="profil"),
]

app/templates/authorization/RegAndAuth.html
{% load static %}



<div id="RegAndAuth">
    <div class=" flex ">
        <div id="closeRegAndAuth">
            <img src="{% static '/icons/arrowLeft.svg'%}" alt="">
        </div>

        <div class="Forms">
            <div class="PanelRegAndAuth">
                <a id="OpenSingIn">Вход</a>
                <a id="OpenSingUp">Регистрация</a>
            </div>
        {% include 'authorization/SingUp.html'%}
        {% include 'authorization/SingIn.html'%}
        </div>
    </div>
</div>

app/templates/authorization/SingIn.html
{% load static %}


<form id="SingIn" action="{% url 'users:singin' %}" method="POST">
    {% csrf_token %}

    {% for fields in formsingin %}
    <div class="input-box">
        <p class="errorText"></p>
        {{fields}}

    </div>
    {% endfor %}

    <button type='submit' class="btn-green">Войти</button>
</form>

app/templates/authorization/SingUp.html
{% load static %}


<form id="SingUp" action="{% url 'users:singup' %}" method="POST">
    {% csrf_token %}

    {% for fields in formsingup %}
    <div class="input-box">
        <p class="errorText"></p>
        {{fields}}

    </div>
    {% endfor %}
    <button type='submit' class="btn-green">Зарегистрироваться</button>
</form>