app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),    
    
    path('', include('shop.urls', namespace="shop")),
    path('account/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path, include

from .views import *

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',  AddCart.as_view(), name="addcart"),
    path('remove/<int:product_id>',  RemoveCart.as_view(), name="removecart"),
    path('update/<int:product_id>/',  UpdateCart.as_view(), name="update"),
    

]

app/orders/urls.py
from django.urls import path, include

from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/',  CreateOrder.as_view(), name="create"),

]

app/cart/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType

from users.models import User
from shop.models import Product



class CartUser(models.Model):
    user = models.OneToOneField(to=User, related_name="cartUser", verbose_name="Пользователя", on_delete=models.CASCADE, null=True)
    pcart = models.JSONField(null=True, blank=True)
    
    

app/cart/forms.py
from django import forms

app/cart/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.http.response import HttpResponseBase
from django.views import View
from django.views.generic.edit import BaseFormView, BaseDeleteView
from django.views.generic import TemplateView, FormView, CreateView, DeleteView
from shop.models import *
from .cart import Cart
from .models import *

class AddCart(CreateView):
    
    def post(self, request, product_id):
        cart = Cart(self.request)
        quantity = self.request.POST.get('quantity')
        product = get_object_or_404(Product, id=product_id)
        context= Product.objects.filter(id=product_id).values('id','name', 'image', 'price')[0]

        cart.add(product=product, quantity=int(quantity), update_quantity=int(quantity))
        number_in_cart : len(self.request.session['cart'])  =  0
        print(number_in_cart)
        data = {
            "id" : context['id'],
            'name' : context['name'],
            "image" :  '/media/' + context['image'],
            "price_total" : int(context['price']) * int(self.request.session['cart'][str(product_id)]['quantity']),
            "quantity": self.request.session['cart'][str(product_id)]['quantity'],
            "all_price_total" :  cart.get_total_price(),
            "number": number_in_cart

        }
        
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
        return render(request, "cart/cartProduct.html", context=data)
        
class RemoveCart(View):
    http_method_names = ['post']
    
    def post(self, request, product_id):
        cart = Cart(self.request)
        
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        number_in_cart =  len(self.request.session['cart']) | 0
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
        return render(request, 'none.html',   status=200)
        



class UpdateCart(FormView):
    def post(self, request, product_id):
        cart = Cart(self.request)
        quantity = self.request.POST.get('quantity')
        print(quantity)
        product = get_object_or_404(Product, id=product_id)
        context= Product.objects.filter(id=product_id).values('id','name', 'price')[0]

        cart.add(product=product, quantity=int(quantity), update_quantity=int(quantity))
        # cart_price = [ i for i in cart.session]
        # print([i for i in cart_price] )

        number_in_cart : 0 =  len(self.request.session['cart']) 
        data = {
            "id" : context['id'],
            'name' : context['name'],
            "price_total" : int(context['price']) * int(self.request.session['cart'][str(product_id)]['quantity']),
            "quantity": self.request.session['cart'][str(product_id)]['quantity'],
            "all_price_total" :  cart.get_total_price(),
            "number": number_in_cart,
        }
        print(self.request.session['cart'])
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
            
        print(data)
        return JsonResponse(data=data)

app/templates/cart/cart.html
{% load static %}

<div id="cartModal">
    <div id="cart">
        <div class="cartHeader">
            <div class="cartTitle">
                <h2>Корзина</h2>
            </div>
            <div class="cartClose" id="cartBtnClose">
                <img src="{% static 'icons/close.svg' %}" alt="">
            </div>

        </div>
        <div class="cartBody">
            {% comment %} {{ request.cart.}} {% endcomment %}
            {% for i in cart%}
                {% with price_total=i.total_price price=i.product.price image=i.product.image.url name=i.product.name quantity=i.quantity id=i.product.id %}
                    {% include "cart/cartProduct.html" %}
                {% endwith %}
            {% endfor %}
            
 
        </div>


    </div>
    <div class="ordering">
        <span > Сумма за всех товары: <span id="TotalPrice">{{ cart.get_total_price }}</span>
        </span>
        <a href="{% url 'orders:create' %}">Оформить заказ</a>
    </div>
</div>

app/templates/cart/cartProduct.html
{% load static %}

<article class="cartProduct">
    <div class="cartProductImage">
        <img src="{{ image }}" alt="">
    </div>
    <div class="cartProductInfo">
        <p class="cartProductName">{{ name }}</p>
        <p > Цена : <span class="total_price">{{ price_total }}</span></p>
        <div class="cartProductNameQuantity">
            <form action="{% url 'cart:update' id %}" method="post"  class="CartUpdate">
                {% csrf_token %}
                <input class='quantityCheck' name="quantity" type="number" value="{{quantity}}"/>
            </form>
        </div>
        <form action="{% url 'cart:removecart' id %}" class="removeCart" method='POST'>
            
            {% csrf_token %}
            <input type="hidden" value="{{id}}" />
            <button type="submit"> Удалить</button><br>
        </form>  
    </div>
</article>