app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),    
    
    path('', include('shop.urls', namespace="shop")),
    path('account/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace="cart")),
    path('orders/', include('orders.urls', namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path, include

from .views import *

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',  AddCart.as_view(), name="addcart"),
    path('remove/<int:product_id>',  RemoveCart.as_view(), name="removecart"),
    path('update/<int:product_id>/',  UpdateCart.as_view(), name="update"),
    

]

app/shop/urls.py
from django.urls import path, include

from .views import *

app_name = 'shop'

urlpatterns = [
    path('',  IndexShow.as_view(), name="home"),
    path('shop/',  ShopView.as_view(), name="shop"),
    path('search/',  SearchView.as_view(), name="search"),
    path('shop/category/<slug:slug_cat>',  CategoryView.as_view(), name="category"),
    path('shop/<slug:slug_product>',  ProductView.as_view(), name="product"),
    
]

app/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import *


app_name = 'users'

urlpatterns = [
    path('singup',  SingUpView.as_view(), name="singup"),
    path('singin',  SingInView.as_view(), name="singin"),
    path('logout',  Logout.as_view(), name="logout"),
    path('profil',  Profil.as_view(), name="profil"),
]

app/cart/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType

from users.models import User
from shop.models import Product



class CartUser(models.Model):
    user = models.OneToOneField(to=User, related_name="cartUser", verbose_name="Пользователя", on_delete=models.CASCADE, null=True)
    pcart = models.JSONField(null=True, blank=True)
    
    

app/cart/forms.py
from django import forms

app/cart/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.http.response import HttpResponseBase
from django.views import View
from django.views.generic.edit import BaseFormView, BaseDeleteView
from django.views.generic import TemplateView, FormView, CreateView, DeleteView
from shop.models import *
from .cart import Cart
from .models import *

class AddCart(CreateView):
    
    def post(self, request, product_id):
        cart = Cart(self.request)
        quantity = self.request.POST.get('quantity')
        product = get_object_or_404(Product, id=product_id)
        context= Product.objects.filter(id=product_id).values('id','name', 'image', 'price')[0]

        cart.add(product=product, quantity=int(quantity), update_quantity=int(quantity))
        number_in_cart : len(self.request.session['cart'])  =  0
        print(number_in_cart)
        data = {
            "id" : context['id'],
            'name' : context['name'],
            "image" :  '/media/' + context['image'],
            "price_total" : int(context['price']) * int(self.request.session['cart'][str(product_id)]['quantity']),
            "quantity": self.request.session['cart'][str(product_id)]['quantity'],
            "all_price_total" :  cart.get_total_price(),
            "number": number_in_cart

        }
        
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
        return render(request, "cart/cartProduct.html", context=data)
        
class RemoveCart(View):
    http_method_names = ['post']
    
    def post(self, request, product_id):
        cart = Cart(self.request)
        
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        number_in_cart =  len(self.request.session['cart']) | 0
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
        return render(request, 'none.html',   status=200)
        



class UpdateCart(FormView):
    def post(self, request, product_id):
        cart = Cart(self.request)
        quantity = self.request.POST.get('quantity')
        print(quantity)
        product = get_object_or_404(Product, id=product_id)
        context= Product.objects.filter(id=product_id).values('id','name', 'price')[0]

        cart.add(product=product, quantity=int(quantity), update_quantity=int(quantity))
        # cart_price = [ i for i in cart.session]
        # print([i for i in cart_price] )

        number_in_cart : 0 =  len(self.request.session['cart']) 
        data = {
            "id" : context['id'],
            'name' : context['name'],
            "price_total" : int(context['price']) * int(self.request.session['cart'][str(product_id)]['quantity']),
            "quantity": self.request.session['cart'][str(product_id)]['quantity'],
            "all_price_total" :  cart.get_total_price(),
            "number": number_in_cart,
        }
        print(self.request.session['cart'])
        if self.request.user.is_authenticated:
            user = CartUser.objects.filter(user=self.request.user)
            user.update(pcart=self.request.session['cart'])
            
        print(data)
        return JsonResponse(data=data)

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/style.css'%}" type="text/css">
    <link rel="shortcut icon" href="{% static 'icons/logo.svg'%}" type="image/x-icon">
    <title>{{ title }}</title>
</head>

<body>
    <header class="headerSucculentum">
        <div class="SucculentumMenu" id="menuBtnOpen">
            <img src="{% static 'icons/menu.svg' %}" alt="">
        </div>
        <div class="titleSucculentum">
            <h1>Succulentum</h1>
        </div>
        <div class="SucculentumCart" id="cartBtnOpen">
            <img src="{% static 'icons/cart.svg' %}" alt="">
            <span id="numberCart">{{ request.session.cart|length  }} </span>
        </div>
    </header>
    {% include 'cart/cart.html' %}
    {% include 'menu.html' %}

    {% block content%}

    {% endblock %}

    <script src="{% static 'js/main.js' %}" type="module"></script>
    <script src="{% static 'js/csrftoken.js' %}" ></script>

</body>


</html>

app/templates/cart.html
{% load static %}

<div id="cartModal">
    <div id="cart">
        <div class="cartHeader">
            <div class="cartTitle">
                <h2>Корзина</h2>
            </div>
            <div class="cartClose" id="cartBtnClose">
                <img src="{% static 'icons/close.svg' %}" alt="">
            </div>

        </div>
        <div class="cartBody">
            {% for i in request.session.cart %}
                {% include "cartProduct.html" with name=i.name image=i.image price=i.price id=i.id type=i.type %}
            {% endfor %}
 
        </div>


    </div>
    <div class="ordering">
        <span> Сумма за все товары:
        </span>
        <button>Оформить заказ</button>
    </div>
</div>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content%}

<main class="wrapperIndex">
    <section>
        <div class="MainPhoto">
            <div class="Slid">
                <img src="{% static 'assets/slide.jpg'%}" alt="">
            </div>
        </div>
        <div class="siteTitle">

            <p>
                <strong>{{ title }}</strong>- это небольшой, но очень тёплый и уютный магазинчик, который влюбляет в
                суккуленты!<br clear>
                <span>Мы - ваши проводники в большой мир маленьких суккулентов.</span>
            </p>
        </div>
    </section>
    <section>
        <div class="productTape">
            <div class="productTapeTitle">
                <h2>Самые популярные товары</h2>
            </div>
            <div class="popularProducts">
                <article class="popularItem">

                </article>
            </div>
        </div>
    </section>



</main>

{% endblock %}

app/templates/menu.html
{% load static %}

<section id="modalMenu">
    <div class="menu">
        <div class="menuTitle">
            <div id="menuBtnClose">
                <img src="{% static 'icons/close.svg' %}" alt="" class="menuClose">
            </div>

            <div class="menuTitleList">
                <div>
                    <ul>
                        <li><a class="menuTitleListHome" href="{% url 'shop:home' %}">Главная</a></li>
                        <li><a class="menuTitleListShop" href="{% url 'shop:shop' %}">Магазин</a></li>
                        <li><a class="menuTitleListDelivery">Доставка</a></li>
                        <li><a class="menuTitleListContact">Контакты</a></li>
                        {% if user.is_superuser %}
                        <li><a class="menuTitleListProfil" href="{% url 'admin:index' %}" >Админка</a></li>
                        {% elif user.is_authenticated %}
                        <li><a class="menuTitleListProfil" href="{% url 'users:profil' %}" >Профиль</a></li>
                        {% endif %}
                        {% if user.is_anonymous %}
                            <li><a id="menuBtnOpenRegAndAuth">Войти</a></li>
                        {% else %}
                            <li><a id="menuBtnOpenRegAndAuth" href="{% url 'users:logout' %}">Выход</a></li>
                        {% endif %}
                        
                    </ul>
                </div>
            </div>

        </div>
        <div class="menuPhoto">
            <img src="{% static '/assets/mainPhoto.jpg' %}" alt="" id="menuMainPhoto">
        </div>
        {% if user.is_anonymous %}
            {% include 'authorization/RegAndAuth.html' %}
        {% endif %}
    </div>
</section>